name: Quarkus CI/CD for Raspberry Pi

on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  checkout-code:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

  setup-environment:
    runs-on: ubuntu-latest
    needs: checkout-code
    steps:
      - name: Set up Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: "17"
          distribution: "temurin"

  build-and-test:
    runs-on: ubuntu-latest
    needs: setup-environment
    environment: staging
    env:
      WORDSAPI_KEY: ${{ secrets.WORDSAPI_KEY }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
      - name: Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and Test
        run: mvn clean verify

  build-and-push-docker-image:
    runs-on: ubuntu-latest
    needs: build-and-test
    steps:
      - name: Build and Push Docker Image using Jib
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: mvn clean package -DskipTests -Dquarkus.container-image.push=true -Dquarkus.docker.buildx.platform=linux/arm64

      - name: Re-tag and Push Image
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
          docker pull ghcr.io/${{ github.repository }}:latest
          docker tag ghcr.io/${{ github.repository }}:latest ghcr.io/${{ github.repository }}:latest
          docker push ghcr.io/${{ github.repository }}:latest

  deploy-to-pi:
    needs: build-and-push-docker-image
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    environment: staging

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set SSH Key Permissions
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Debug Environment Variables
        run: |
          echo "PUBLIC_IP: ${{ secrets.PUBLIC_IP }}"
          echo "PI_USERNAME: ${{ secrets.PI_USERNAME }}"

      - name: Deploy to Raspberry Pi
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.PUBLIC_IP }}
          username: ${{ secrets.PI_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            docker login ghcr.io -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }}
            docker pull ghcr.io/${{ github.repository }}:latest
            docker stop tadiag-quarkus-app || true
            docker rm tadiag-quarkus-app || true
            docker run -d \
              --name tadiag-quarkus-app \
              -p 8080:8080 \
              -e DB_HOST=${{ secrets.PUBLIC_IP }} \
              -e WORDSAPI_KEY=${{ secrets.WORDSAPI_KEY }} \
              --health-cmd="curl --fail http://localhost:8080/q/health || exit 1" \
              --health-interval=30s \
              --health-timeout=10s \
              --health-retries=3 \
              --health-start-period=30s \
              ghcr.io/${{ github.repository }}:latest